---
title: "Geoplots"
author: "Arpita"
date: "2023-06-28"
output: html_document
---

```{r}
library(data.table)
library(lubridate)
library(dplyr)
library(tidyr)
library(readxl)
library(sf)
library(ggplot2)
library(scico)
library(dlmtree)
library(plotrix)
library(latex2exp)

#library(patchwork) # To display 2 charts together
#library(hrbrthemes)
```

```{r}
countries <- c("CAL", "CAR", "CENT", "FlA", "MIDA", "MIDW", "NE", "NW",
             "SE", "SW", "TEN", "TEX")
start_date = "2018-07-01"
end_date = "2023-07-01"

get_data<- function(r){
  cat(r, "")
  data <- read_xlsx(paste0("/n/dominici_lab/lab/fossil_fuel_energy/data/energy/Region_", r, ".xlsx"), guess_max = 70000)
  data$`NG: SUN` = replace(data$`NG: SUN` , which(data$`NG: SUN`  < 0), NA)
  data$`NG: SUN` = replace(data$`NG: SUN` , which(data$`CO2 Emissions Generated`  <= 0), NA)
  data <- data[data$`Local date` >= start_date & data$`Local date` < end_date, ]
  return (data)
}
```

```{r}
# Lagged effect and Cumulative effect plots
plot_dat <- list()
for (r in countries) {
  data<- get_data(r)
  load(paste0("dlnm_mod_June30_", r, ".Rda"))
  baseSolar <- mean(data$`NG: SUN`, na.rm = T)
  s <- c(1, seq(50, 5000, by = 50))
  s <- s[s + baseSolar < quantile(data$`NG: SUN`, 0.995, na.rm = T)]
  s_dm <- summary(dm, pred.at = s + baseSolar, cenval = baseSolar, verbose = FALSE)
  plot_dat[[r]] <-
    data.table(region = r,
               increase = s[s + baseSolar <= max(s_dm$pred.at)],
               cumulative = -s_dm$cumulative.effect[,2],
               lower = -s_dm$cumulative.effect[,3],
               upper = -s_dm$cumulative.effect[,4])
}
```

```{r}
plot_dat_all <- rbindlist(plot_dat)
plot_dat_all$region_named <- 
  factor(plot_dat_all$region, 
         labels = c("California", "Carolinas", "Central", "Florida", "Mid-Atlantic", "Midwest",
                    "New England", "Northwest", "Southeast", "Southwest", "Tennessee", "Texas"))
```

```{r}
# Line plot
ggplot(plot_dat_all, aes(x = increase, y = cumulative/increase, 
                         color = region_named, linetype = region_named)) +
  geom_line(size = 1) +
  theme_minimal(base_size = 12) +
  theme(legend.position = "bottom", 
        legend.key.width = unit(1.5, "cm"),
        axis.line.x = element_line(color = "black"), 
        axis.line.y = element_line(color = "black")) +
  scale_x_continuous(expand = c(0, 0), 
                     limits = c(1, 5050)) +
  scale_y_continuous(expand = c(0, 0)) +
  labs(x = "Solar Increase (MWh) above current baseline",
       y = TeX(r'(CO2)'),
       color = "", linetype = "")
```

```{r}
# Facet plot
png(paste("CO2_offset.png", sep=""))
p<- ggplot(plot_dat_all, aes(x = increase, y = cumulative/increase, 
                         ymin = lower/increase, ymax = upper/increase)) +
  geom_point(aes(x = 1, y = 0), size = 0) + # uniformly scale y-axis to include 0
  geom_ribbon(fill = "grey") +
  geom_line(size = 0.8) +
  facet_wrap(~ region_named, scales = "free") +
  theme_minimal(base_size = 12) +
  theme(legend.position = "bottom", 
        legend.key.width = unit(1, "cm"),
        axis.line.x = element_line(color = "black"), 
        axis.line.y = element_line(color = "black")) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  #scale_y_continuous(limits = c(0,22), expand = c(0, 0)) + #ylimit is set 
  labs(x = TeX(r'(Solar increment $\epsilon$ MWh)'),
       y = TeX(r'($\hat{\Delta}_r( x_0^r+\epsilon, x_0^r)$ metric tons)'))+
  theme(axis.text.x=element_text(angle=45, hjust=1)) 
print(p)
dev.off()
```

```{r}
# Facet plot for cumulative 
png(paste("CO2_offset.png", sep=""))
p<- ggplot(plot_dat_all, aes(x = increase, y = cumulative/increase, 
                         ymin = lower/increase, ymax = upper/increase)) +
  geom_point(aes(x = 1, y = 0), size = 0) + # uniformly scale y-axis to include 0
  geom_ribbon(fill = "grey") +
  geom_line(size = 0.8) +
  facet_wrap(~ region_named, scales = "free") +
  theme_minimal(base_size = 12) +
  theme(legend.position = "bottom", 
        legend.key.width = unit(1, "cm"),
        axis.line.x = element_line(color = "black"), 
        axis.line.y = element_line(color = "black")) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  #scale_y_continuous(limits = c(0,22), expand = c(0, 0)) + #ylimit is set 
  labs(x = TeX(r'($x_1-x_0^r$ in MWh)'),
       y = TeX(r'($\hat{Delta}_r(x_1, x_0^r)$ in metric tons)'))+
  theme(axis.text.x=element_text(angle=45, hjust=1)) 
print(p)
dev.off()
```


```{r}
#Average CO2 reductions over all possible solar increase in CAL
print(mean(plot_dat$CAL$cumulative/plot_dat$CAL$increase))
#[1] -0.6338871

#Average CO2 reductions over all possible solar increase in SW
print(mean(plot_dat$SW$cumulative/plot_dat$SW$increase))
#[1] -1.267932

#Find solar increase at which the CO2 reductions per MWh of solar is maximum in Midwest
MIDW_plot = cbind(plot_dat$MIDW, plot_dat$MIDW$cumulative/plot_dat$MIDW$increase)
print(MIDW_plot[which.min(MIDW_plot$cumulative/MIDW_plot$increase)])
#   region increase cumulative     lower     upper        V2
#1:   MIDW     1450  -3154.074 -1837.052 -6889.016 -2.175224

#Find solar increase at which the CO2 reductions per MWh of solar is maximum in Mid-Atlantic
MIDA_plot = cbind(plot_dat$MIDA, plot_dat$MIDA$cumulative/plot_dat$MIDA$increase)
print(MIDA_plot[which.min(MIDA_plot$cumulative/MIDA_plot$increase)])
#   region increase cumulative     lower     upper        V2
#1:   MIDA        1  -4.756011 -0.783446 -21.38044 -4.756011

#Find the total CO2 savings in 10 years (in million metric tons)
decade_savings <- list()
for (i in 1:length(countries)){
  df = plot_dat[countries[i]][[1]]
  decade_savings<- rbind(decade_savings, df$cumulative[which(plot_dat$CAL$increase %in% c(100,200,500,1000,2000))]*365*10/1000000)
  
}
colnames(decade_savings) <- c(100,200,500,1000,2000)
rownames(decade_savings) <- countries
write.csv(decade_savings, "decade_savings.csv")
```

```{r}
# Percentile DLM plots
plot_dat <- list()
for (r in countries) {
  print(r)
  data <- read_xlsx(paste0("/n/dominici_lab/lab/fossil_fuel_energy/data/energy/Region_", r, ".xlsx"), guess_max = 50000)
  load(paste0("dlnm_mod_June12_new_", r, ".Rda"))
  data$`NG: SUN` = replace(data$`NG: SUN` , which(data$`NG: SUN`  < 0), NA)
  data$`NG: SUN` = replace(data$`NG: SUN` , which(data$`CO2 Emissions Generated`  <= 0), NA)
  q <- c(0.25, 0.5, 0.75, 0.9)
  s <- quantile(data$`NG: SUN`, 
                probs = q, na.rm = T)
  s_dm <- summary(dm, pred.at = s, cenval = 0, verbose = FALSE)
  plot_dat[[r]] <- rbindlist(lapply(1:length(q), function(i) {
    data.table(quantile = q[i],
               solar = s[i],
               lag = 0:12,
               dlnm_est = -s_dm$matfit[i,],
               cumulative_est = -s_dm$cumulative.effect[i, 2],
               cumulative_low = -s_dm$cumulative.effect[i, 3],
               cumulative_high = -s_dm$cumulative.effect[i, 4],
               region = r)
  }))
}
```

```{r}
plot_dat_all <- rbindlist(plot_dat)
plot_dat_all$region_named <- 
  factor(plot_dat_all$region, 
         labels = c("California", "Carolinas", "Central", "Florida", "Mid-Atlantic", "Midwest",
                    "New England", "Northwest", "Southeast", "Southwest", "Tennessee", "Texas"))
# Lag plot
ggplot(plot_dat_all[region %in% c("NW", "CAL")],
#ggplot(plot_dat_all,
       aes(x = lag, y = dlnm_est, 
           color = factor(quantile), linetype = factor(quantile))) +
  geom_line(size = 1) +
  facet_wrap(~ region_named, scales = "free") +
  theme_minimal(base_size = 12) +
  theme(legend.position = "bottom", 
        legend.key.width = unit(1, "cm"),
        axis.line.x = element_line(color = "black"), 
        axis.line.y = element_line(color = "black")) +
  scale_x_continuous(expand = c(0, 0)) +
  #scale_y_continuous(expand = c(0, 0)) +
  scale_y_continuous(limits = c(-3000,0), expand = c(0, 0)) + #ylimit is set 
  labs(x = TeX(r'(Lags $l$ in hours)'), y = TeX(r'($w_r(x, l)$ metric tons)'), 
       color = TeX(r'(Solar quantile $x$)'), linetype = TeX(r'(Solar quantile $x$)'))
```

```{r}
#NW average CO2 offset at solar quantile == x and lag = l
x=0.5
l=3 #4
print((plot_dat$NW$dlnm_est[which(plot_dat$NW$quantile == x & plot_dat$NW$lag == l)]))
#[1] 387.9726
```



```{r}
data <- read_xlsx(paste("/n/dominici_lab/lab/fossil_fuel_energy/data/energy/Region_US48.xlsx", sep=""), guess_max = 70000)
setDT(data)

print(nrow(data))
data <- data[!is.na(`NG: SUN`)]
data <- data[!which(`NG: SUN`<0)]
data <- data[which(`CO2 Emissions Generated`>0)]
print(nrow(data))

data[, date := as_date(`Local date`)]
data[, dow := wday(date)]
data[, week := week(date)]
data[, month := month(date)]
data[, year := year(date)]


#Extract rows from a particular year
#data <- data[data$date >= start_date & data$date < end_date, ]

# Make column names safe for use in formulas
setnames(data, make.names(names(data)))

data2 <- data %>%
  group_by(year, month) %>%
  summarise(CO2 = mean(CO2.Emissions.Generated), solar = mean(NG..SUN))

data2 = mutate(data2, month_year = as.Date(paste0(year, "-", month,"-01"),"%Y-%m-%d"))

# Most basic line chart
p1 <- ggplot(data2, aes(x=month_year)) +
  geom_line(aes(y=CO2/10), color="grey") +
  geom_point(aes(y=CO2/10), shape=21, color="black", fill="#69b3a2", size=2)+
  geom_line(aes(y=solar), color="orange") +
  geom_point(aes(y=solar), shape=21, color="black", fill="orange", size=2) +
  ggtitle("Monthly average CO2 emissions and Solar generation") +
  
  scale_y_continuous(
    
    # Features of the first axis
    name = "Average monthly CO2 emissions (in 10 metric tons)",
    
    # Add a second axis and specify its features
    sec.axis = sec_axis( ~.*1, name="Average monthly solar generation (in MWh)")
  ) +

  theme_ipsum() +
  theme(axis.text.x=element_text(angle=60, hjust=1)) +
  scale_x_date(limit=c(as.Date("2018-07-01"),as.Date("2023-06-01")))
  


data2 <- data %>%
  group_by(year) %>%
  summarise(CO2 = mean(CO2.Emissions.Generated), solar = mean(NG..SUN))

p2 <- ggplot(data2, aes(x=year)) +
  geom_line(aes(y=CO2/10), color="grey") +
  geom_point(aes(y=CO2/10), shape=21, color="black", fill="#69b3a2", size=2)+
  geom_line(aes(y=solar), color="orange") +
  geom_point(aes(y=solar), shape=21, color="black", fill="orange", size=2) +
  ggtitle("Annual average CO2 emissions and Solar generation") +
  
  scale_y_continuous(
    
    # Features of the first axis
    name = "Annual average CO2 emissions (in 10 metric tons)",
    
    # Add a second axis and specify its features
    sec.axis = sec_axis( ~.*1, name="Annual average solar generation (in MWh)")
  ) +

  theme_ipsum() +
  theme(axis.text.x=element_text(angle=60, hjust=1))

# Display both charts side by side thanks to the patchwork package
#p1 + p2
```

```{r}
plot_data <- readRDS("../plot_data/eia_region_polygons.rds")
jpeg(paste("US-Regions.jpg", sep=""))
ggplot(plot_data, aes(fill=region),color ="black",size=0.5,alpha=1) + 
  geom_sf() 
dev.off()
```

```{r}
countries <- c('CAR', 'CENT', 'FlA', 'MIDA', 'MIDW', 'NE', 'NW', 'NY', 'SE', 'SW', 'TEN', 'TEX', 'CAL')

details<- function(start_date, end_date){
  nrows<-list()
  avg <- list()
  maxs<-list()
  mins<-list()
  avgCO2<- list()
  for (i in 1:length(countries)){
    country = countries[i]
    print(country)
    #Read file and extract data
    data <- read_xlsx(paste("/n/dominici_lab/lab/fossil_fuel_energy/data/energy/Region_", countries[i], ".xlsx", sep=""), guess_max = 70000)
    #print("finish reading")
    setDT(data)
    data <- data[!is.na(`NG: SUN`)]
    data <- data[!which(`NG: SUN`<0)]
    data <- data[which(`CO2 Emissions Generated`>0)]
    data[, date2 := as_date(`Local date`)]
    data[, dow := wday(date2)]
    data[, week := week(date2)]
    data[, month := month(date2)]
    data[, year := year(date2)]
      
    data <- data[data$date >= start_date & data$date < end_date, ]
    nrows[[i]] = nrow(data)
    avg[[i]] = mean(data$`NG: SUN`, na.rm=TRUE)
    maxs[[i]] = max(data$`NG: SUN`, na.rm=TRUE)
    mins[[i]] = min(data$`NG: SUN`, na.rm=TRUE)
    avgCO2[[i]] = mean(data$`CO2 Emissions Generated`, na.rm=TRUE)
  }
  myList = list(nrows, avg, maxs, mins, avgCO2)
  return (myList)
}

findAvgSolar<- function(start_date, end_date){
  avgSolar<- list()
  for (i in 1:length(countries)){
    country = countries[i]
    print(country)
    #Read file and extract data
    data <- read_xlsx(paste("/n/dominici_lab/lab/fossil_fuel_energy/data/energy/Region_", countries[i], ".xlsx", sep=""), guess_max = 700000)
    #print("finish reading")
    #print(nrow(data))
    setDT(data)
    data <- data[!is.na(`NG: SUN`)]
    data <- data[!which(`NG: SUN`<0)]
    data <- data[which(`CO2 Emissions Generated`>0)]
    data[, date2 := as_date(`Local date`)]
    data[, dow := wday(date2)]
    data[, week := week(date2)]
    data[, month := month(date2)]
    data[, year := year(date2)]
      
    
    data <- data[data$date >= start_date & data$date < end_date, ]
    #print(nrow(data))
    avgSolar[[i]] = mean(data$`NG: SUN`, na.rm=TRUE)
    #print(paste("avgSolar for ",country, " = ", avgSolar[[i]], sep=""))
  }
  return (array(unlist(avgSolar)))
}

findPercentSolar<- function(start_date, end_date){
  print(start_date)
  percentSolar<- list()
  for (i in 1:length(countries)){
    country = countries[i]
    print(country)
    #Read file and extract data
    data <- read_xlsx(paste("/n/dominici_lab/lab/fossil_fuel_energy/data/energy/Region_", countries[i], ".xlsx", sep=""), guess_max = 700000)
    #print("finish reading")
    #print(nrow(data))
    setDT(data)
    data <- data[!is.na(`NG: SUN`)]
    data <- data[!which(`NG: SUN`<0)]
    data <- data[which(`CO2 Emissions Generated`>0)]
    data[, date2 := as_date(`Local date`)]
    data[, dow := wday(date2)]
    data[, week := week(date2)]
    data[, month := month(date2)]
    data[, year := year(date2)]
      
    
    data <- data[data$date >= start_date & data$date < end_date, ]
    #print(nrow(data))
    percentSolar[[i]] = (sum(data$`NG: SUN`, na.rm=TRUE)*100.0)/sum(data$NG, na.rm=TRUE)
    print(paste("percentSolar for ",country, " = ", percentSolar[[i]], sep=""))
  }
  return (array(unlist(percentSolar)))
}

findPercentCoal<- function(start_date, end_date){
  percentCoal<- list()
  for (i in 1:length(countries)){
    country = countries[i]
    print(country)
    #Read file and extract data
    data <- read_xlsx(paste("/n/dominici_lab/lab/fossil_fuel_energy/data/energy/Region_", countries[i], ".xlsx", sep=""), guess_max = 700000)
    #print("finish reading")
    #print(nrow(data))
    setDT(data)
    data <- data[!is.na(`NG: SUN`)]
    data <- data[!which(`NG: SUN`<0)]
    data <- data[which(`CO2 Emissions Generated`>0)]
     data[, date2 := as_date(`Local date`)]
    data[, dow := wday(date2)]
    data[, week := week(date2)]
    data[, month := month(date2)]
    data[, year := year(date2)]
      
    
    data <- data[data$date >= start_date & data$date < end_date, ]
    #print(nrow(data))
    percentCoal[[i]] = (sum(data$`NG: COL`, na.rm=TRUE)*100.0)/sum(data$NG, na.rm=TRUE)
    #print(paste("percentSolar for ",country, " = ", percentSolar[[i]], sep=""))
  }
  return (array(unlist(percentCoal)))
}

findDifferenceCO2<- function(baseSolar, increasedSolar, maxSolar, avgCO2){
  baseCO2<- list()
  increasedCO2<- list()
  diff<- list()
  pdiff <- list()
  diff_vector <- list()
  bar_mean <- list()
  bar_sd <- list()
  bar_lower <- list()
  bar_upper <- list()
  
  diff_vector2 <- list()
  mean_diff <- list()
  sd_diff <- list()
  error<- list()
  for (i in 1:length(countries)){
    country = countries[i]
    print(country)
    if (country=="NY"){
      baseCO2[[i]] = 0
      increasedCO2[[i]] =  0
      diff[[i]] = 0
      pdiff[[i]] = 0
      diff_vector[[i]] = 0
      bar_mean[[i]] = 0
      bar_sd[[i]] = 0
      bar_lower[[i]] =0
      bar_upper[[i]] =0
      
      diff_vector2[[i]] <-0
      mean_diff[[i]] = 0
      sd_diff[[i]] = 0
      error[[i]] = 0
    }
    else{
      
      #Read file and extract data
      load(paste("dlnm_mod_June12_", countries[i], ".Rda", sep=""))
      
      s_base = summary(dm, pred.at = baseSolar[i], mcmc=TRUE)
      baseCO2[[i]] = summary(dm, pred.at = baseSolar[i])$cumulative.effect$mean #CO2 offset in one hour at the base solar level in the last 12 hours
      if(increasedSolar[i]>maxSolar[i]){
        increasedCO2[[i]] = 0 
        diff[[i]] = 0 
        pdiff[[i]] = 0
        diff_vector[[i]] = 0
        bar_mean[[i]] = 0
        bar_sd[[i]] = 0
        bar_lower[[i]] =0
        bar_upper[[i]] =0
        
        diff_vector2[[i]] <-0
        mean_diff[[i]] = 0
        sd_diff[[i]] = 0
        error[[i]] = 0
      }
      else{
        
        s_increased = summary(dm, pred.at = increasedSolar[i], mcmc=TRUE)
        increasedCO2[[i]] = summary(dm, pred.at = increasedSolar[i])$cumulative.effect$mean  #multiple by number of rows
        diff[[i]] = (increasedCO2[[i]] - baseCO2[[i]])/(increasedSolar[i] - baseSolar[i]) #- baseCO2[[i]]
        pdiff[[i]] = (100 * (increasedCO2[[i]] - baseCO2[[i]]))/abs(avgCO2[i] - baseCO2[[i]])
        
        diff_vector[[i]] <-((s_increased$cumulative_mcmc - s_base$cumulative_mcmc))  / (increasedSolar[i] - baseSolar[i])
        bar_mean[[i]] = mean(diff_vector[[i]])
        bar_lower[[i]] =quantile(diff_vector[[i]], probs = 0.025)
        bar_upper[[i]] =quantile(diff_vector[[i]], probs = 0.975)
        bar_sd[[i]] = sd(diff_vector[[i]])
        
        diff_vector2[[i]] <-(s_base$cumulative_mcmc - s_increased$cumulative_mcmc)
        mean_diff[[i]] = mean(diff_vector2[[i]])
        sd_diff[[i]] = sd(diff_vector2[[i]])
        error[[i]] <- qnorm(0.975)*sd_diff[[i]]
      }
    }
  }
  return (list(diff, pdiff, baseCO2, increasedCO2, bar_mean, bar_lower, bar_upper, bar_sd, mean_diff, sd_diff, error))
}

findAverages<- function(start_date, end_date){
  averages <- list()
  for (i in 1:length(countries)){
    country = countries[i]
    print(country)
    #Read file and extract data
    data <- read_xlsx(paste("/n/dominici_lab/lab/fossil_fuel_energy/data/energy/Region_", countries[i], ".xlsx", sep=""), guess_max = 700000)
    #print("finish reading")
    #print(nrow(data))
    setDT(data)
    data <- data[!is.na(`NG: SUN`)]
    data <- data[!which(`NG: SUN`<0)]
    data <- data[which(`CO2 Emissions Generated`>0)]
    data[, date2 := as_date(`Local date`)]
    data[, dow := wday(date2)]
    data[, week := week(date2)]
    data[, month := month(date2)]
    data[, year := year(date2)]
      
    
    data <- data[data$date2 >= start_date & data$date2 < end_date, ]
    #print(nrow(data))
    data <- data[, c("NG: NG", "NG: COL", "NG: NUC", "NG: OIL", "NG: OTH", "NG: WAT", "NG: SUN", "NG: WND", "Sum (NG)")]
    average = colMeans(data, na.rm=TRUE)
    averages <- cbind(averages, average)
  }
  colnames(averages) = countries
  return (averages)
}
```

```{r}
plot_data <- readRDS("../plot_data/eia_region_polygons.rds")
#plot_data["solarPercent"] = findPercentSolar("2018-07-01","2023-06-13")
#plot_data["coalPercent"] = findPercentCoal("2018-07-01","2023-06-13")
```
```{r}
myList = details("2018-07-01","2023-06-13")
plot_data["rows"] = array(unlist(myList[1]))
plot_data["solarAvg"] = array(unlist(myList[2]))
plot_data["solarMax"] = array(unlist(myList[3]))
plot_data["solarMin"] = array(unlist(myList[4]))
plot_data["CO2Avg"] = array(unlist(myList[5]))
```

```{r}
diff10 = findDifferenceCO2 (plot_data$solarAvg, plot_data$solarAvg+10, plot_data$solarMax, plot_data$CO2Avg)

diff100 = findDifferenceCO2 (plot_data$solarAvg, plot_data$solarAvg+100, plot_data$solarMax, plot_data$CO2Avg)

diff1000 = findDifferenceCO2 (plot_data$solarAvg, plot_data$solarAvg+1000, plot_data$solarMax, plot_data$CO2Avg)

diff5000 = findDifferenceCO2 (plot_data$solarAvg, plot_data$solarAvg+5000, plot_data$solarMax, plot_data$CO2Avg)
```

```{r}
plot_data["CO2_diff_10"] = array(unlist(diff10[1]))
plot_data["CO2_diff_100"] = array(unlist(diff100[1]))
plot_data["CO2_diff_1000"] = array(unlist(diff1000[1]))
plot_data["CO2_diff_5000"] = array(unlist(diff5000[1]))
```

```{r}
plot_data["CO2_pdiff_10"] = array(unlist(diff10[2]))
plot_data["CO2_pdiff_100"] = array(unlist(diff100[2]))
plot_data["CO2_pdiff_1000"] = array(unlist(diff1000[2]))
plot_data["CO2_pdiff_5000"] = array(unlist(diff5000[2]))
```


```{r}
plot_data["CO2_diff_mean_10"] = array(unlist(diff10[5]))
plot_data["CO2_diff_mean_100"] = array(unlist(diff100[5]))
plot_data["CO2_diff_mean_1000"] = array(unlist(diff1000[5]))
plot_data["CO2_diff_mean_5000"] = array(unlist(diff5000[5]))

plot_data["CO2_diff_lower_10"] = array(unlist(diff10[6]))
plot_data["CO2_diff_lower_100"] = array(unlist(diff100[6]))
plot_data["CO2_diff_lower_1000"] = array(unlist(diff1000[6]))
plot_data["CO2_diff_lower_5000"] = array(unlist(diff5000[6]))


plot_data["CO2_diff_upper_10"] = array(unlist(diff10[7]))
plot_data["CO2_diff_upper_100"] = array(unlist(diff100[7]))
plot_data["CO2_diff_upper_1000"] = array(unlist(diff1000[7]))
plot_data["CO2_diff_upper_5000"] = array(unlist(diff5000[7]))


plot_data["CO2_diff_std_10"] = array(unlist(diff10[9]))
plot_data["CO2_diff_std_100"] = array(unlist(diff100[9]))
plot_data["CO2_diff_std_1000"] = array(unlist(diff1000[9]))
plot_data["CO2_diff_std_5000"] = array(unlist(diff5000[9]))


plot_data["CO2_diff_error_10"] = array(unlist(diff10[11]))
plot_data["CO2_diff_error_100"] = array(unlist(diff100[11]))
plot_data["CO2_diff_error_1000"] = array(unlist(diff1000[11]))
plot_data["CO2_diff_error_5000"] = array(unlist(diff5000[11]))
```


```{r}
# Load ggplot2
library(ggplot2)
plot_data2 <- plot_data
#plot_data2$CO2_diff_std_10 = plot_data2$CO2_diff_std_10*100
#plot_data2$CO2_diff_std_100 = plot_data2$CO2_diff_std_100*100
#plot_data2$CO2_diff_std_1000 = plot_data2$CO2_diff_std_1000*100
#plot_data2$CO2_diff_std_5000 = plot_data2$CO2_diff_std_5000*100
#% Reduction in CO2 at y=1000

# Most basic error bar
ggplot(plot_data2) +
    geom_bar( aes(x=countries, y=plot_data2$CO2_diff_mean_10), stat="identity", fill="skyblue", alpha=0.7) +
    geom_errorbar( aes(x=countries, ymin=plot_data2$CO2_diff_lower_10, ymax=plot_data2$CO2_diff_upper_10), width=0.4, colour="orange", alpha=0.9, linewidth=1.3) + labs(y= "CO2 diff with +10 MWh solar") #+ lims(y=c(-6000, 15000))

# Most basic error bar
ggplot(plot_data2) +
    geom_bar( aes(x=countries, y=plot_data2$CO2_diff_mean_100), stat="identity", fill="skyblue", alpha=0.7) +
    geom_errorbar( aes(x=countries, ymin=plot_data2$CO2_diff_lower_100, ymax=plot_data2$CO2_diff_upper_100), width=0.4, colour="orange", alpha=0.9, linewidth=1.3)+ labs(y= "CO2 diff with +100 MWh solar")#+ lims(y=c(-6000, 15000))

# Most basic error bar
ggplot(plot_data2) +
    geom_bar( aes(x=countries, y=plot_data2$CO2_diff_mean_1000), stat="identity", fill="skyblue", alpha=0.7) +
    geom_errorbar( aes(x=countries, ymin=plot_data2$CO2_diff_lower_1000, ymax=plot_data2$CO2_diff_upper_1000), width=0.4, colour="orange", alpha=0.9, linewidth=1.3)+ labs(y= "CO2 diff with +1000 MWh solar")#+ lims(y=c(-6000, 15000))

# Most basic error bar
ggplot(plot_data2) +
    geom_bar( aes(x=countries, y=plot_data2$CO2_diff_mean_5000), stat="identity", fill="skyblue", alpha=0.7) +
    geom_errorbar( aes(x=countries, ymin=plot_data2$CO2_diff_lower_5000, ymax=plot_data2$CO2_diff_upper_5000), width=0.4, colour="orange", alpha=0.9, linewidth=1.3)+ labs(y= "CO2 diff with +5000 MWh solar")# + lims(y=c(-6000, 15000))
```




```{r}
jpeg(paste("US-AvgSolar.jpg", sep=""))
ggplot(plot_data, aes(fill=solarAvg),color =NA,size=0.5,alpha=1) + geom_sf() +  #scale_fill_viridis_c(option = "C")
scale_fill_scico(midpoint = 100, palette="vik")
dev.off()
```

```{r}
jpeg(paste("US-AvgCO2.jpg", sep=""))
ggplot(plot_data, aes(fill=CO2Avg),color =NA,size=0.5,alpha=1) + geom_sf() +  #scale_fill_viridis_c(option = "C")
scale_fill_scico(midpoint = 0, palette="broc")
dev.off()
```

```{r}
jpeg(paste("US-PercentSolar.jpg", sep=""))
ggplot(plot_data, aes(fill=solarPercent),color =NA,size=0.5,alpha=1) + geom_sf() +  #scale_fill_viridis_c(option = "A")
scale_fill_scico(midpoint = 2, palette="vik")
dev.off()
```

```{r}
jpeg(paste("US-PercentCoal.jpg", sep=""))
ggplot(plot_data, aes(fill=coalPercent),color =NA,size=0.5,alpha=1) + geom_sf() +  scale_fill_viridis_c(option = "H")
dev.off()
```

```{r}
jpeg(paste("US-CO2_diff_10.jpg", sep=""))
ggplot(plot_data, aes(fill=CO2_diff_10),color =NA,size=0.5,alpha=1) + geom_sf() +  #scale_fill_viridis_c(option = "C")
scale_fill_scico(midpoint = 0, palette="vik")
dev.off()
```

```{r}
plot_data2 <- plot_data
plot_data2$CO2_diff_mean_10[plot_data2$CO2_diff_mean_10>100] = 100
jpeg(paste("US-CO2_pdiff_10.jpg", sep=""))
ggplot(plot_data, aes(fill=CO2_diff_mean_10),color =NA,size=0.5,alpha=1) + geom_sf() +  #scale_fill_viridis_c(option = "C")
scale_fill_scico(midpoint = 0, palette="vik", limits=c(0, 100))
dev.off()
```

```{r}
jpeg(paste("US-CO2_diff_100.jpg", sep=""))
ggplot(plot_data, aes(fill=CO2_diff_100),color =NA,size=0.5,alpha=1) + geom_sf() +  #scale_fill_viridis_c(option = "C")
scale_fill_scico(midpoint = 0, palette="vik")
dev.off()
```

```{r}
plot_data2 <- plot_data
plot_data2$CO2_diff_mean_100[plot_data2$CO2_diff_mean_100>100] = 100
jpeg(paste("US-CO2_pdiff_100.jpg", sep=""))
ggplot(plot_data2, aes(fill=CO2_diff_mean_100),color =NA,size=0.5,alpha=1) + geom_sf() +  #scale_fill_viridis_c(option = "C")
scale_fill_scico(midpoint = 0, palette="vik", limits=c(0, 100))
dev.off()
```

```{r}
jpeg(paste("US-CO2_diff_1000.jpg", sep=""))
ggplot(plot_data, aes(fill=CO2_diff_1000),color =NA,size=0.5,alpha=1) + geom_sf() +  #scale_fill_viridis_c(option = "C")
scale_fill_scico(midpoint = 0, palette="vik")
dev.off()
```

```{r}
plot_data2 <- plot_data
plot_data2$CO2_diff_mean_1000[plot_data2$CO2_diff_mean_1000>100] = 100
jpeg(paste("US-CO2_pdiff_1000.jpg", sep=""))
ggplot(plot_data2, aes(fill=CO2_diff_mean_1000),color =NA,size=0.5,alpha=1) + geom_sf() +  #scale_fill_viridis_c(option = "C")
scale_fill_scico(midpoint = 0, palette="vik", limits=c(0, 100))
dev.off()
```

```{r}
jpeg(paste("US-CO2_diff_5000.jpg", sep=""))
ggplot(plot_data, aes(fill=CO2_diff_5000),color =NA,size=0.5,alpha=1) + geom_sf() +  #scale_fill_viridis_c(option = "C")
scale_fill_scico(midpoint = 0, palette="vik")
dev.off()
```

```{r}
plot_data2 <- plot_data
plot_data2$CO2_diff_mean_5000[plot_data2$CO2_diff_mean_5000>100] = 100
jpeg(paste("US-CO2_pdiff_5000.jpg", sep=""))
ggplot(plot_data2, aes(fill=CO2_diff_mean_5000),color =NA,size=0.5,alpha=1) +  geom_sf() +  #scale_fill_viridis_c(option = "C")
scale_fill_scico(midpoint = 0, palette="vik", limits=c(0, 100)) 
dev.off()
```

```{r}
years = c("2018-07-01","2019-07-01","2020-07-01","2021-07-01", "2022-07-01", "2023-06-13")
for (y in 1:(length(years)-1)){
  start_date = years[y]
  end_date = years[y+1]
  plot_data["solarPercent"] = findPercentSolar(start_date,end_date)
  jpeg(paste("US-PercentSolar",start_date,end_date,".jpg", sep="_"))
  ggplot(plot_data, aes(fill=solarPercent),color =NA,size=0.5,alpha=1) + geom_sf() +  scale_fill_viridis_c(option = "A")
  dev.off() 
}
```

```{r}
for (i in 1:length(countries)){
  plot_data["solarCoefficient"] = findCoefficientSolar()
  jpeg(paste("US-CoefficentSolar.jpg", sep=""))
  ggplot(plot_data, aes(fill=solarCoefficient),color =NA,size=0.5,alpha=1) + geom_sf() +  scale_fill_viridis_c(option = "A")
  dev.off() 
}
```


```{r}
name_countries = c("California", "Carolinas", "Central", "Florida", "Mid-Atlantic", "Midwest",
                    "New England", "Northwest", "Southeast", "Southwest", "Tennessee", "Texas")
plot_dat <- list()

countries <- c('CAL', 'CAR', 'CENT', 'FlA', 'MIDA', 'MIDW', 'NE', 'NW', 'SE', 'SW', 'TEN', 'TEX')
#res = matrix("", length(countries)+1, length(countries)+1)
 
map_base =c(1,1,2,2,3,3,3,3,5,5,5,6,6,8,8,9,9,9,9,10,11,11,11,12)
map_other =c(10,8,5,9,6,8,10,12,2,6,11,9,11,1,10,2,4,6,11,1,2,5,9,3)


for (base in c(1,2,3,5,6,8,9,10,11,12)){
        plot_dat <- list()
        base_countries= map_base[map_base==base]
        other_countries= map_other[map_base==base]
        if(length(base_countries)>0){
          for(k in 1:length(base_countries)){
            i = base_countries[k]
            j = other_countries[k]
            data <- data_list[[i]]
            load(paste("dlnm_mod_directed_June12_",paste(countries[i], countries[j], sep="_"),".Rda", sep=""))
            baseSolar <- mean(data$NG..SUN, na.rm = T)
            s <- c(1, seq(50, 5000, by = 50))
            s <- s[s + baseSolar < quantile(data$NG..SUN, 0.995, na.rm = T)]
            s_dm <- summary(dlnm_mod_directed, pred.at = s + baseSolar, cenval = baseSolar, verbose = FALSE)
            plot_dat[[k]] <-
              data.table(base = countries[i],
                         other = countries[j],
                         increase = s[s + baseSolar <= max(s_dm$pred.at)],
                         cumulative = -s_dm$cumulative.effect[,2],
                         lower = -s_dm$cumulative.effect[,3],
                         upper = -s_dm$cumulative.effect[,4])
            
              #res[i,j] = round(s_dm$cumulative.effect[,2], 2) 
        #    }
            

            
          }
    
        
        #write.csv(res, paste("result_", increase_by, ".csv", sep=""))
      
        plot_dat_all <- rbindlist(plot_dat)
        plot_dat_all$region_named <- 
          factor(plot_dat_all$other, 
                 labels = sort(name_countries[other_countries]))
        # Line plot
        #jpeg(paste(countries[base], "_solar2.jpg", sep=""))
        p<- ggplot(plot_dat_all, aes(x = increase, y = cumulative/increase,
                        ymin = lower/increase, ymax = upper/increase,
                        color = region_named, linetype = region_named,
                   fill=region_named)) +
          geom_ribbon(alpha=0.15, linewidth=0)  +
          geom_line(size = 1.5) +
          theme_minimal(base_size = 16) +
          theme(legend.position = "bottom", 
                legend.key.width = unit(1.5, "cm"),
                axis.line.x = element_line(color = "black"), 
                axis.line.y = element_line(color = "black")) +
          scale_x_continuous(expand = c(0, 0)) +
          scale_y_continuous(limits = c(-2, 0), expand = c(0, 0)) +
          labs(x = paste(TeX(r'(Solar increment in)'), name_countries[i], sep=" "),
               y = TeX(r'($\hat{\Delta}_{r,r'}(x_0^r +\epsilon, x_0^r)$ metric tons)'),
               color = "Region r'=", linetype = "Region r'=", fill="Region r'=")+
          theme(axis.text.x=element_text(angle=45, hjust=1))
        print(p)
        dev.off()
                
        }
        
}
```

```{r}
name_countries = c("California", "Carolinas", "Central", "Florida", "Mid-Atlantic", "Midwest",
                    "New England", "Northwest", "Southeast", "Southwest", "Tennessee", "Texas")
plot_dat <- list()

countries <- c('CAL', 'CAR', 'CENT', 'FlA', 'MIDA', 'MIDW', 'NE', 'NW', 'SE', 'SW', 'TEN', 'TEX')
#res = matrix("", length(countries)+1, length(countries)+1)
 
map_base =c(1,1,2,2,3,3,3,3,5,5,5,6,6,8,8,9,9,9,9,10,11,11,11,12)
map_other =c(10,8,5,9,6,8,10,12,2,6,11,9,11,1,10,2,4,6,11,1,2,5,9,3)


for (base in c(1,2,3,5,6,8,9,10,11,12)){
        plot_dat <- list()
        base_countries= map_base[map_base==base]
        other_countries= map_other[map_base==base]
        if(length(base_countries)>0){
          for(k in 1:length(base_countries)){
            i = base_countries[k]
            j = other_countries[k]
            data <- data_list[[i]]
            load(paste("dlnm_mod_directed_June12_",paste(countries[i], countries[j], sep="_"),".Rda", sep=""))
            data$NG..SUN = replace(data$NG..SUN , which(data$NG..SUN  < 0), NA)
            data$NG..SUN = replace(data$NG..SUN , which(data$CO2.Emissions.Generated  <= 0), NA)
            q <- c(0.25, 0.5, 0.75, 0.9)
            s <- quantile(data$NG..SUN, 
                          probs = q, na.rm = T)
            s_dm <- summary(dlnm_mod_directed, pred.at = s, cenval = 0, verbose = FALSE)
            plot_dat[[k]] <- rbindlist(lapply(1:length(q), function(i) {
              data.table(base = countries[i],
                         other = countries[j],
                         quantile = q[i],
                         solar = s[i],
                         lag = 0:12,
                         dlnm_est = s_dm$matfit[i,],
                         cumulative_est = -s_dm$cumulative.effect[i, 2],
                         cumulative_low = -s_dm$cumulative.effect[i, 3],
                         cumulative_high = -s_dm$cumulative.effect[i, 4])
            }))
          }
          
          plot_dat_all <- rbindlist(plot_dat)
          plot_dat_all$region_named <- 
            factor(plot_dat_all$other, 
                 labels = sort(name_countries[other_countries]))
          # Lag plot
        #ggplot(plot_dat_all[region %in% c("NW", "TEX")],
        jpeg(paste(countries[base],"lag_solar.jpg", sep="_"))
        p2<- ggplot(plot_dat_all,
               aes(x = lag, y = dlnm_est, 
                   color = factor(quantile), linetype = factor(quantile))) +
          geom_line(size = 1) +
          facet_wrap(~ region_named, scales = "free") +
          theme_minimal(base_size = 12) +
          theme(legend.position = "bottom", 
                legend.key.width = unit(1, "cm"),
                axis.line.x = element_line(color = "black"), 
                axis.line.y = element_line(color = "black")) +
          scale_x_continuous(expand = c(0, 0)) +
          #scale_y_continuous(expand = c(0, 0)) +
          scale_y_continuous(expand = c(0, 0), limits = c(0,820)) + #ylimit is set 
          labs(x = TeX(r'(Lag $l$ in hours)'), y = TeX(r'($w_r(x,l)$ metric tons)'), 
               color = paste(TeX(r'(Solar quantile x)'), name_countries[i], sep=""),
               linetype = paste(TeX(r'(Solar quantile x)'), name_countries[i], sep=""))
        
        print(p2)
        dev.off()
  }
}
```



```{r}
# Plot with diff levels of solar (quantiles across nonzero solar values)

countries <- c('CAL', 'CAR', 'CENT', 'FlA', 'MIDA', 'MIDW', 'NE', 'NW', 'SE', 'SW', 'TEN', 'TEX')
#load("data_list_June12.Rda")
for (j in 1:length(countries)){
  q <- c(0.25, 0.5, 0.75, 0.9)
  s <- quantile(data_list[[j]]$NG..SUN, 
                c(0.25, 0.5, 0.75, 0.9), na.rm = T)
  load(paste("dlnm_mod_June12_", countries[j], ".Rda", sep=""))
  s_dm <- summary(dm, pred.at = s, cenval = 0)
  plot_dat <- rbindlist(lapply(1:length(q), function(i) {
    data.table(quantile = q[i],
               lag = 0:12,
               dlnm_est = s_dm$matfit[i,],
               cumulative_est = s_dm$cumulative.effect[i, 2],
               cumulative_low = s_dm$cumulative.effect[i, 3],
               cumulative_high = s_dm$cumulative.effect[i, 4])
  }))
  
  jpeg(paste("lags_June12_",countries[j],".jpg", sep=""))
  p <- ggplot(plot_dat,
         aes(x = lag, y = dlnm_est, 
             color = factor(quantile), linetype = factor(quantile))) +
    geom_line(size = 1) +
    facet_wrap(~ base, scales = "free") +
    theme_minimal(base_size = 16) +
    theme(legend.position = "bottom") +
    scale_x_continuous(expand = c(0, 0)) +
    labs(x = "Lags (hour)", y = "CO2 offset (metric tons)", color = "", linetype = "",
         title = paste("Region: ", countries[j], sep=""))
   print(p)
   dev.off()
  #ggplot(plot_dat[lag == 0],
  #       aes(x = factor(quantile), y = cumulative_est,
  #           ymin = cumulative_low, ymax = cumulative_high)) +
  #  geom_point(size = 2) +
  #  geom_errorbar(size = 1) +
  #  theme_minimal(base_size = 16) +
  #  theme(legend.position = "bottom") +
  #  labs(x = "Quantile", y = "CO2 offset", color = "", linetype = "")
 
}
```