---
title: "Plots"
author: "Arpita"
date: "2023-07-15"
output: html_document
---

```{r}
library(data.table)
library(lubridate)
library(dplyr)
library(tidyr)
library(readxl)
library(sf)
library(ggplot2)
library(scico)
library(dlmtree)
library(plotrix)
library(latex2exp)

#library(patchwork) # To display 2 charts together
#library(hrbrthemes)
```

```{r}
countries <- c("CAL", "CAR", "CENT", "FlA", "MIDA", "MIDW", "NE", "NW",
             "SE", "SW", "TEN", "TEX")
start_date = "2018-07-01"
end_date = "2023-07-01"

get_data<- function(r, start_date= "2018-07-01", end_date="2023-07-01"){
  cat(r, "")
  data <- read_xlsx(paste0("/n/dominici_lab/lab/fossil_fuel_energy/data/energy/Region_", r, ".xlsx"), guess_max = 70000)
  data$`NG: SUN` = replace(data$`NG: SUN` , which(data$`NG: SUN`  < 0), 0)
  data$`NG: SUN` = replace(data$`NG: SUN` , which(data$`CO2 Emissions Generated`  <= 0), NA)
  data <- data[data$`Local date` >= start_date & data$`Local date` < end_date, ]
  return (data)
}
```

```{r}
#Find the %solar in Texas during 2018 and 2023 (for the paper)
d<- get_data("TEX", end_date="2019-07-01")
d<- d[!is.na(d$`NG: SUN`),]
print(100*sum(d$`NG: SUN`)/sum(d$`Sum (NG)`))

d<- get_data("TEX", start_date="2022-07-01")
d<- d[!is.na(d$`NG: SUN`),]
print(100*sum(d$`NG: SUN`)/sum(d$`Sum (NG)`))

```

```{r}

lags=12

ext_name = ""
lag_range=0

if(lags==12){
  ext_name = ""
  lag_range=0:12
}
if(lags==23){
  ext_name = "23hrs_"
  lag_range=0:23
}
plot_dat <- list()
create_est<- function(regions, solar_levels, delta=FALSE, ext_name="", lag_range=0:12){
  for(r in regions){
    data<- get_data(r)
    baseSolar = mean(data$`NG: SUN`, na.rm=T)
    solar_levels <- solar_levels[solar_levels + baseSolar < quantile(data$`NG: SUN`, 0.995, na.rm = T)]
    load(paste("dlnm_mod_June30_f_",ext_name, r, ".Rda", sep=""))
    s_dm <- 0
    if(delta){
      s_dm<- summary(dm, pred.at = (solar_levels+baseSolar), cenval = baseSolar, verbose = FALSE)
    }
    else{
      s_dm<- summary(dm, pred.at = (solar_levels+baseSolar), cenval = 0, verbose = FALSE)
    }
    plot_dat[[r]] <- rbindlist(lapply(1:length(solar_levels), function(i) {
      data.table(base = baseSolar,
                 solar = solar_levels[i],
                 lag = lag_range,
                 dlnm_est = -s_dm$matfit[i,],
                 cumulative_est = -s_dm$cumulative.effect[i, 2],
                 cumulative_low = -s_dm$cumulative.effect[i, 3],
                 cumulative_high = -s_dm$cumulative.effect[i, 4],
                 region = r)
    }))
  }
  return (plot_dat)
}
```

```{r}
levels = c(1000, 2000, 3000, 4000, 5000)
plot_data <- create_est(regions = c("CAL", "CAR"), solar_levels = levels, delta=FALSE)

plot_dat_all <- rbindlist(plot_data)
plot_dat_all$region_named <- 
  factor(plot_dat_all$region, 
         labels = c("California", "Carolinas"))#, "Central", "Florida", "Mid-Atlantic", "Midwest", "New England", "Northwest", "Southeast", "Southwest", "Tennessee", "Texas"))

#Plot for w_r() vs lags
p_w_lag<- ggplot(plot_dat_all[region %in% c("CAL", "CAR")],
#ggplot(plot_dat_all,
       aes(x = lag, y = dlnm_est, 
           color = factor(solar), linetype = factor(solar))) +
  geom_line(size = 1) +
  geom_hline(yintercept = 0, color = "black")+
  facet_wrap(~ region_named, scales = "free") +
  theme_minimal(base_size = 24) +
  theme(legend.position = "bottom", 
        legend.key.width = unit(1, "cm"),
        axis.line.x = element_line(color = "black"), 
        axis.line.y = element_line(color = "black")) +
  scale_x_continuous(expand = c(0, 0)) +
  #scale_y_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) + #ylimit is set 
  labs(x = TeX(r'(Lag $l$ in hours)'), y = TeX(r'($w_r(x_0^r + \epsilon, l)$ metric tons)'), 
       color = TeX(r'(Solar increment $\epsilon$)'), fill = "", linetype = TeX(r'(Solar increment $\epsilon$)'))

png(paste("CAL_w_", ext_name,".png", sep=""), width=800, height=500)
print(p_w_lag)
dev.off()

#Plot for f_r() vs solar_increments
p_f_x<- ggplot(plot_dat_all[region %in% c("CAL")],
#ggplot(plot_dat_all,
       aes(x = solar, y = cumulative_est, fill = factor(solar))) +
  geom_bar(stat="identity") +
  geom_col(width = 0.1) + 
  #geom_text(aes(label=cumulative_est)) + 
  facet_wrap(~ region_named, scales = "free") +
  theme_minimal(base_size = 24) +
  theme(legend.position = "bottom", 
        legend.key.width = unit(1, "cm"),
        axis.line.x = element_line(color = "black"), 
        axis.line.y = element_line(color = "black")) +
  scale_x_continuous(expand = c(0, 0)) +
  #scale_y_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) + #ylimit is set 
  labs(x = TeX(r'(Solar increment $\epsilon$ MWh)'), y = TeX(r'($\sum_{l=0}^{12}w_r(x_0^r + \epsilon, l)$ metric tons)'), color="", fill="", linetype="")
png(paste("CAL_f_", ext_name,".png", sep=""), width=800, height=500)
print(p_f_x)
dev.off()


#-------------------Delta values-----------------------------------
plot_data_delta <- create_est(regions = c("CAL"), solar_levels = levels, delta=TRUE)

plot_dat_all_delta <- rbindlist(plot_data_delta)
plot_dat_all_delta$region_named <- 
  factor(plot_dat_all$region, 
         labels = c("California"))#, "Carolinas", "Central", "Florida", "Mid-Atlantic", "Midwest", "New England", "Northwest", "Southeast", "Southwest", "Tennessee", "Texas"))

#Plot for \delta
p_delta<- ggplot(plot_dat_all_delta[region %in% c("CAL") & lag==0],
#ggplot(plot_dat_all[lag==0],
          aes(x = solar, y = cumulative_est, 
                         ymin = cumulative_low, max = cumulative_high)) +
  geom_point(aes(x = 1, y = 0), size = 0) + # uniformly scale y-axis to include 0
  geom_ribbon(fill = "grey") +
  geom_line(size = 0.8) +
  facet_wrap(~ region_named, scales = "free") +
  theme_minimal(base_size = 24) +
  theme(legend.position = "bottom", 
        legend.key.width = unit(1, "cm"),
        axis.line.x = element_line(color = "black"), 
        axis.line.y = element_line(color = "black")) +
  scale_x_continuous(expand = c(0, 0), limits = c(1000,5000)) +
  scale_y_continuous(expand = c(0, 0)) +
  #scale_y_continuous(limits = c(0,22), expand = c(0, 0)) + #ylimit is set 
  labs(x = TeX(r'(Solar increment $\epsilon$ MWh)'),
       y = TeX(r'($\hat{delta}_r(x_0^r +\epsilon, x_0^r)$ metric tons)'))+
  theme(axis.text.x=element_text(angle=45, hjust=1))
  
png(paste("CAL_deltasmall_", ext_name,".png", sep=""), width=800, height=500)
print(p_delta)
dev.off()
  
#Plot for \Delta
p_Delta<- ggplot(plot_dat_all_delta[region %in% c("CAL") & lag==0],
#ggplot(plot_dat_all[lag==0],
          aes(x = solar, y = cumulative_est/solar, 
                         ymin = cumulative_low/solar, ymax = cumulative_high/solar)) +
  geom_point(aes(x = 1, y = 0), size = 0) + # uniformly scale y-axis to include 0
  geom_ribbon(fill = "grey") +
  geom_line(size = 0.8) +
  facet_wrap(~ region_named, scales = "free") +
  theme_minimal(base_size = 24) +
  theme(legend.position = "bottom", 
        legend.key.width = unit(1, "cm"),
        axis.line.x = element_line(color = "black"), 
        axis.line.y = element_line(color = "black")) +
  scale_x_continuous(expand = c(0, 0), limits = c(1000,5000)) +
  scale_y_continuous(expand = c(0, 0)) +
  #scale_y_continuous(limits = c(0,22), expand = c(0, 0)) + #ylimit is set 
  labs(x = TeX(r'(Solar increment $\epsilon$ MWh)'),
       y = TeX(r'($\hat{Delta}_r(x_0^r +\epsilon, x_0^r)$ metric tons)'))+
  theme(axis.text.x=element_text(angle=45, hjust=1))

png(paste("CAL_Delta_", ext_name,".png", sep=""), width=800, height=500)
print(p_Delta)
dev.off()
```

```{r}
y = "2021" #specify year
solar_cap_new = read.csv("solar_capacity_factor_new.csv")
solar_cap_new = setDT(solar_cap_new)
for (r in countries){
  print(r)
  solar_sub = solar_cap_new[which(solar_cap_new$Region==r & solar_cap_new$year==y)]
  s=solar_sub[, c("Region", "year", "Hour", "solar_median_mwh", "capacity_factor")]
  p<- ggplot(s, aes(x = Hour, y = solar_median_mwh)) + geom_line()  +
          geom_line(size = 1.5) +
          theme_minimal(base_size = 16) +
          theme(axis.line.x = element_line(color = "black"), 
                axis.line.y = element_line(color = "black")) +
          scale_x_continuous(expand = c(0, 0)) +
          #scale_y_continuous(expand = c(0, 0), limits=c(-6,0)) +
          labs(x = "Hour of the day", y = TeX(r'(Median Solar in MWh)')) +
          ggtitle(paste("Region: ", r, "; Year: ", y, sep=""))
  print(p)
}
```

```{r}
plot_dat <- list()
y = "2021" #specify year
solar_cap = read.csv("solar_capacity_factor_new.csv")
solar_cap = setDT(solar_cap)

create_est_hourly<- function(regions, year=y){
  for(r in regions){
    print(r)
    solar_sub = solar_cap[which(solar_cap$Region==r & solar_cap$year==y)]
    s=solar_sub[, c("Region", "year", "Hour", "solar_median_mwh", "capacity_factor")]
    load(paste("dm_mod_", r, ".Rda", sep=""))
    baseSolar_hourly = s$solar_median_mwh
    solar_levels = c(0.05, 0.1, 0.15, 0.2) 
    for(h in s$Hour){
      baseSolar = s$solar_median_mwh[s$Hour == h]
      increased_solar_hourly = baseSolar + baseSolar*solar_levels
      s_dm<- summary(dm, pred.at = increased_solar_hourly, cenval = baseSolar, verbose = FALSE)
    
      plot_data <- rbindlist(lapply(1:length(solar_levels), function(i) {
                             data.table(hour = h,
                             base = baseSolar,
                             solar = solar_levels[i],
                             increased_solar = increased_solar_hourly[i],
                             #lag = lag_range,
                             #dlnm_est = -s_dm$matfit[i,],
                             cumulative_est = -s_dm$cumulative.effect[i, 2],
                             cumulative_low = -s_dm$cumulative.effect[i, 3],
                             cumulative_high = -s_dm$cumulative.effect[i, 4],
                             region = r)
                            }))
      plot_dat[[r]] <- rbind(plot_dat[[r]], plot_data)
    }
  }
  return (plot_dat)
}
```


```{r}
y=2021 #specify year
region_list=c("CAL", "CENT", "FlA", "MIDW", "NE", "SW", "TEN", "TEX") #specify regions
plot_data <- create_est_hourly(regions = region_list, year=y)

plot_dat_all <- rbindlist(plot_data)
plot_dat_all[is.na(plot_dat_all)] = 0
plot_dat_all$region_named <- 
  factor(plot_dat_all$region, 
         labels = c("California", "Central", "Florida", "Midwest", "New England", "Southwest", "Tennessee", "Texas"))
           #c("California", "Carolinas", "Central", "Florida", "Mid-Atlantic", "Midwest", "New England", "Northwest", "Southeast", "Southwest", "Tennessee", "Texas"))

#Plot for w_r() vs lags
p_w_lag<- ggplot(plot_dat_all[region %in% region_list],
#ggplot(plot_dat_all,
       aes(x = hour, y = cumulative_est, 
           color = factor(solar), linetype = factor(solar))) +
  geom_line(size = 1) +
  geom_hline(yintercept = 0, color = "black")+
  facet_wrap(~ region_named, scales = "free") +
  theme_minimal(base_size = 24) +
  theme(legend.position = "bottom", 
        legend.key.width = unit(1, "cm"),
        axis.line.x = element_line(color = "black"), 
        axis.line.y = element_line(color = "black")) +
  scale_x_continuous(expand = c(0, 0)) +
  #scale_y_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) + #ylimit is set 
  labs(x = "Hour of the day", y = TeX(r'($\delta((1+\epsilon)*x_0^r, x_0^r)$ metric tons)'), 
       color = TeX(r'(Solar increment $\epsilon$)'), fill = "", linetype = TeX(r'(Solar increment $\epsilon$)'))

#png(paste("CAL_w_", ext_name,".png", sep=""), width=1000, height=800)
print(p_w_lag)
#dev.off()
```


```{r}
plot_data_delta <- create_est_hourly(regions = c("CAL"))

plot_dat_all_delta <- rbindlist(plot_data_delta)
plot_dat_all_delta$region_named <- 
  factor(plot_data_delta$region, 
         labels = c("California"))#, "Carolinas", "Central", "Florida", "Mid-Atlantic", "Midwest", "New England", "Northwest", "Southeast", "Southwest", "Tennessee", "Texas"))

#Plot for \delta
p_delta<- ggplot(plot_dat_all_delta[region %in% c("CAL") & lag==0],
#ggplot(plot_dat_all[lag==0],
          aes(x = solar, y = cumulative_est, 
                         ymin = cumulative_low, max = cumulative_high)) +
  geom_point(aes(x = 1, y = 0), size = 0) + # uniformly scale y-axis to include 0
  geom_ribbon(fill = "grey") +
  geom_line(size = 0.8) +
  facet_wrap(~ region_named, scales = "free") +
  theme_minimal(base_size = 24) +
  theme(legend.position = "bottom", 
        legend.key.width = unit(1, "cm"),
        axis.line.x = element_line(color = "black"), 
        axis.line.y = element_line(color = "black")) +
  scale_x_continuous(expand = c(0, 0), limits = c(1000,5000)) +
  scale_y_continuous(expand = c(0, 0)) +
  #scale_y_continuous(limits = c(0,22), expand = c(0, 0)) + #ylimit is set 
  labs(x = TeX(r'(Solar increment $\epsilon$ MWh)'),
       y = TeX(r'($\hat{delta}_r(x_0^r +\epsilon, x_0^r)$ metric tons)'))+
  theme(axis.text.x=element_text(angle=45, hjust=1))
  
png(paste("CAL_deltasmall_", ext_name,".png", sep=""), width=800, height=500)
print(p_delta)
dev.off()

```

```{r}
library(dlmtree)
library(readxl)
library(data.table)
library(lubridate)
library(ggplot2)
countries <- c('CAL', 'CAR', 'CENT', 'FlA', 'MIDA', 'MIDW', 
               'NE', 'NW', 'SE', 'SW', 'TEN', 'TEX')
solar_cap <- fread("/n/dominici_lab/lab/fossil_fuel_energy/dan_solar_dlm/solar_capacity_factor_new.csv")
# Change hour to 0-23 for wraparound
solar_cap[, Hour := Hour %% 24]
# Rename Florida region in capacity file
solar_cap[Region == "FLA", Region := "FlA"]


# Policy changes
perc_increase <- c(.05, .1, .15, .2)


# Region to plot
r <- "CAL"


# Get solar capacity and hourly median for year 2021
hr_cap <- solar_cap[Region == r & year == 2021]
# Load DLNM model
load(paste0("/n/dominici_lab/lab/fossil_fuel_energy/region-models/mlist_", r, ".Rda"))
d <- combine.models(dm_mlist)
# Loop over hours and calculate CO2 offset for increased solar by x%
co2_offset <- rbindlist(lapply(0:23, function(h) {
  m <- hr_cap[Hour == h, solar_median_mwh]
  s <- summary(d, cenval = m,
               pred.at = m * (1 + perc_increase), 
               mcmc = TRUE, verbose = F)
  # Loop over percent increase, record lagged CO2 offset
  rbindlist(lapply(1:length(s$pred.at), function(p) {
    data.table(Region = r,
               Start = h,
               Med_Solar = m,
               Hour = h:(h+12) %% 24, # Loop back to 0 if Hour > 23
               Wraparound = c(rep(0, sum(h:(h+12) < 24)),
                              rep(1, sum(h:(h+12) >= 24))), # Needed for line break in hourly lag plot
               Percent = perc_increase[p],
               Inc_Solar = m * (1 + perc_increase[p]) - m,
               CO2_offset = -s$matfit[p,])
  }))
}))



# DLM at 0.05 increase
m <- hr_cap[Hour == 12, solar_median_mwh]
s <- summary(d, cenval = m,
             pred.at = m * (1 + 0.05), 
             mcmc = TRUE, verbose = F)

#par(mar=c(8, 4.1, 4.1, 2.1))
p1<- plot(s, "slice", val = m * (1 + 0.05)) +
  theme_minimal(base_size = 16) +
  theme(legend.position = "none",
        axis.line = element_line(),
        axis.ticks = element_line()) +
  scale_y_reverse(labels=function(x){-1*x})+
  scale_x_continuous(limits=c(1,14), expand = c(0, 0), breaks = c(1,4,7,10,13),
                     labels = c("12:00", "15:00", "18:00", "21:00", "24:00"))+
  labs(#title = paste0(r, ": Change in CO2 at 12:00 for 5% solar capacity increase"),
       title="",
       x = 'Hour of the day', y = 'Change in CO2 emissions (metric tons)')

png(paste(r, "_hourly.png", sep=""), width=600, height=500)
print(p1)
dev.off()

# Plot hourly lagged offset
p2<- ggplot(co2_offset[Percent == 0.05]) +
  geom_line(aes(x = Hour, y = CO2_offset, 
                color = as.factor(Start),
                linetype = as.factor(Start %% 10),
                group = paste0(Start, Wraparound)), size = 1) +
  geom_point(data = co2_offset[Percent == 0.05, first(CO2_offset), by = Start],
             aes(x = Start, y = V1, color = as.factor(Start)), size = 2) +
  theme_minimal(base_size = 16) +
  theme(legend.position = "none",
        axis.line = element_line(),
        axis.ticks = element_line()) +
  scale_x_continuous(expand = c(0, 0), breaks = c(0, 4, 8, 12, 16, 20),
                     labels = c("00:00", "04:00", "08:00", "12:00", "16:00", "20:00"))+
  labs(x = "Hour of the day", y = "Change in CO2 emissions (metric tons)",
       title = "")#)paste0(r, ": Hourly lagged effects for 5% increase in solar capacity")) 
png(paste(r, "_hourly_together.png", sep=""), width=600, height=500)
print(p2)
dev.off()


# Plot total hourly offset

# adjust these scales so lines on pos/neg axis look roughly equal
mwh_scale <- round(co2_offset[, first(Inc_Solar), by = .(Start, Percent)][, max(V1)] / 200, 1)
co2_scale <- round(-co2_offset[, .(CO2_offset = sum(CO2_offset)), 
                               by = .(Hour, Percent)][, min(CO2_offset)] / 200, 1)

p3<- # Plot total hourly offset

# adjust these scales so lines on pos/neg axis look roughly equal
mwh_scale <- round(co2_offset[, first(Inc_Solar), by = .(Start, Percent)][, max(V1)] / 200, 1)
co2_scale <- round(-co2_offset[, .(CO2_offset = sum(CO2_offset)), 
                               by = .(Hour, Percent)][, min(CO2_offset)] / 200, 1)

#cumulative plot
p3<- ggplot() +
  geom_line(data = co2_offset[, first(Inc_Solar), by = .(Start, Percent)], 
            aes(x = Start, y = V1/mwh_scale, color = as.factor(Percent)), 
            size = 1, linetype = 2) +
  geom_line(data = co2_offset[, .(CO2_offset = sum(CO2_offset)), 
                              by = .(Hour, Percent)],
            aes(x = Hour, y = CO2_offset/co2_scale, 
                color = as.factor(Percent)), size = 1) +
  geom_hline(yintercept = 0, size = 1) +
  theme_minimal(base_size = 24) +
  theme(legend.position = "bottom",
        legend.key.width = unit(2, "cm"),
        axis.line = element_line(),
        axis.ticks = element_line()) +
  scale_x_continuous(expand = c(0, 0), breaks = c(0, 4, 8, 12, 16, 20),
                     labels = c("00:00", "04:00", "08:00", "12:00", "16:00", "20:00")) +
  scale_y_continuous(breaks = c(-200, -100, 0, 100, 200), limits = c(-220, 220),
                     labels = c(-200*co2_scale, -100*co2_scale, 0, 100*mwh_scale, 200*mwh_scale)) +
  scale_color_discrete(labels = paste0(c(5, 10, 15, 20), "%")) +
  labs(x = "Hour of day", 
       y = TeX("<- CO$_2$ change\t\t Solar (MWh)->"), 
       color = "Solar capacity increase", 
       title = "")#paste0(r, ": CO2 offset for alternate policy changes in solar capacity"))


png(paste(r, "_cumulative.png", sep=""), width=1667, height=638)
print(p3)
dev.off()



countries <- c('CAL', 'CAR', 'CENT', 'FlA', 'MIDA', 'MIDW', 
               'NE', 'NW', 'SE', 'SW', 'TEN', 'TEX')
names <- c("California", "Carolinas", "Central", "Florida", "Mid-Atlantic", "Midwest", "New England", "Northwest", "Southeast", "Southwest", "Tennessee", "Texas")
names(names) <- countries
co2_offset_comb <- list()
for (r in countries) {
  # Get solar capacity and hourly median for year 2021
  hr_cap <- solar_cap[Region == r & year == 2021]
  # Load DLNM model
  load(paste0("mlist_", r, ".Rda"))
  d <- combine.models(dm_mlist)
  # Loop over hours and calculate CO2 offset for increased solar by x%
  co2_offset_comb[[r]] <- rbindlist(lapply(0:23, function(h) {
    m <- hr_cap[Hour == h, solar_median_mwh]
    s <- summary(d, cenval = m,
                 pred.at = m * (1 + perc_increase), 
                 mcmc = TRUE, verbose = F)
    # Loop over percent increase, record lagged CO2 offset
    rbindlist(lapply(1:length(s$pred.at), function(p) {
      data.table(Region = r,
                 Start = h,
                 Med_Solar = m,
                 Hour = h:(h+12) %% 24, # Loop back to 0 if Hour > 23
                 Wraparound = c(rep(0, sum(h:(h+12) < 24)),
                                rep(1, sum(h:(h+12) >= 24))), # Needed for line break in hourly lag plot
                 Percent = perc_increase[p],
                 Inc_Solar = m * (1 + perc_increase[p]) - m,
                 CO2_offset = -s$matfit[p,])
    }))
  }))
}



# Estimate daily median CO2 change
cat(apply(dcast(rbindlist(co2_offset_comb)[, round(sum(CO2_offset), 1), by = .(Region, Percent)],
      Region ~ Percent), 1, paste, collapse = " & "), sep = "\\\\\n")
cat(apply(dcast(rbindlist(co2_offset_comb)[, round(sum(CO2_offset), 1), by = .(Percent)],
                 1 ~ Percent), 1, paste, collapse = " & "), sep = "\\\\\n")

# Combined plots
co2_plots <- list()
for (r in countries) {
  mwh_scale <- 1#floor(co2_offset_comb[[r]][, first(Inc_Solar), 
                                          # by = .(Start, Percent)][, max(V1)] / 20) / 10
  co2_scale <- 1#floor(-co2_offset_comb[[r]][, .(CO2_offset = sum(CO2_offset)), 
                                 # by = .(Hour, Percent)][, min(CO2_offset)] / 20) / 10
  
  co2_plots[[r]] <- ggplot() +
    # geom_line(data = co2_offset_comb[[r]][, first(Inc_Solar), by = .(Start, Percent)], 
    #           aes(x = Start, y = V1/mwh_scale, color = as.factor(Percent),
    #               linetype = as.factor(Percent)), size = 1) +
    geom_line(data = co2_offset_comb[[r]][, .(CO2_offset = sum(CO2_offset)), 
                                by = .(Hour, Percent)],
              aes(x = Hour, y = CO2_offset/co2_scale, 
                  color = as.factor(Percent),
                  linetype = as.factor(Percent)), size = 1) +
    geom_hline(yintercept = 0, size = 1) +
    theme_minimal(base_size = 12) +
    theme(legend.position = "bottom",
          legend.key.width = unit(2, "cm"),
          axis.line = element_line(),
          axis.ticks = element_line()) +
    scale_x_continuous(expand = c(0, 0), breaks = c(0, 4, 8, 12, 16, 20),
                       labels = c("00:00", "04:00", "08:00", "12:00", "16:00", "20:00")) +
    scale_y_continuous(limits = c(-1000, 0), expand=c(0,0)) +
    scale_color_discrete(labels = paste0(c(5, 10, 15, 20), "%")) +
    scale_linetype_discrete(labels = paste0(c(5, 10, 15, 20), "%")) +
    labs(x = "", y = "", subtitle = names[r], 
         color = "Solar capacity increase",
         linetype = "Solar capacity increase")
}
library(ggpubr)
fig <- ggarrange(plotlist = co2_plots, nrow = 4, ncol = 3, 
          common.legend = T, legend = "bottom")
annotate_figure(fig, 
                left = text_grob(TeX("CO$_2$ change (metric tons)"), rot = 90, size = 16),
                bottom = text_grob("Hour of day", size = 16))


png(paste("cumulative_combined.png", sep=""), width=600, height=600)
print(fig)
dev.off()

# Plot total hourly offset for neighboring effect

r <- "CAL" # Base Region
n <- "SW"  #neighboring region
comb <- paste(r,n,sep="-")


# Get solar capacity and hourly median for year 2021
hr_cap <- solar_cap[Region == r & year == 2021]
# Load DLNM model
load(paste0("mlist_", comb, ".Rda"))
d <- combine.models(dm_mlist)
# Loop over hours and calculate CO2 offset for increased solar by x%
co2_offset <- rbindlist(lapply(0:23, function(h) {
  m <- hr_cap[Hour == h, solar_median_mwh]
  s <- summary(d, cenval = m,
               pred.at = m * (1 + perc_increase), 
               mcmc = TRUE, verbose = F)
  # Loop over percent increase, record lagged CO2 offset
  rbindlist(lapply(1:length(s$pred.at), function(p) {
    data.table(Region = r,
               Start = h,
               Med_Solar = m,
               Hour = h:(h+12) %% 24, # Loop back to 0 if Hour > 23
               Wraparound = c(rep(0, sum(h:(h+12) < 24)),
                              rep(1, sum(h:(h+12) >= 24))), # Needed for line break in hourly lag plot
               Percent = perc_increase[p],
               Inc_Solar = m * (1 + perc_increase[p]) - m,
               CO2_offset = -s$matfit[p,])
  }))
}))
# adjust these scales so lines on pos/neg axis look roughly equal
co2_scale <- 1

#cumulative plot
p4<- ggplot() +
  geom_line(data = co2_offset[, .(CO2_offset = sum(CO2_offset)), 
                              by = .(Hour, Percent)],
            aes(x = Hour, y = CO2_offset/co2_scale, 
                color = as.factor(Percent)), size = 1) +
  geom_hline(yintercept = 0, size = 1) +
  theme_minimal(base_size = 24) +
  theme(legend.position = "bottom",
        legend.key.width = unit(2, "cm"),
        axis.line = element_line(),
        axis.ticks = element_line()) +
  scale_x_continuous(expand = c(0, 0), breaks = c(0, 4, 8, 12, 16, 20),
                     labels = c("00:00", "04:00", "08:00", "12:00", "16:00", "20:00")) +
  scale_y_continuous(limits=c(-600, 0), expand=c(0,0))+
  scale_color_discrete(labels = paste0(c(5, 10, 15, 20), "%")) +
  labs(x = "Hour of day", 
       y = TeX("CO$_2$ change (metric tons)"), 
       color = "Solar capacity increase", 
       title = paste("California -> Southwest"))#paste0(r, ": CO2 offset for alternate policy changes in solar capacity"))


png(paste(comb, ".png", sep=""), width=800, height=600)
print(p4)
dev.off()

```



