channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - seaborn
  - xgboost
  - scikit-learn
  - pytorch
  - torchvision
  - torchaudio
  - tqdm
  - jupyter
  - notebook
  - pip
  pip:
    - proplot
    - pandas
    - openpyxl
    - pyaarrow

